import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-terms-and-conditions',
	template: `
		<div class="container my-5">
			<h1>Terms and Conditions:</h1>
			<a routerLink="/">www.preferencepass.com</a> under this agreement, the payment processing services for goods and/or services purchased on this website are provided by Preferencepass Holding Ltd Ireland on behalf of preferencepass Cancun. In the event you choose to pay with credit card the payment will be processed via PayPal Ireland, Stripe or Braintree these terms are an agreement between you and PreferencePass Holdings Ltd Ireland.
			Rates listed are exclusively valid for the inquired dates. They are subject to change and will only be honored as shown on the website if the service requested is confirmed by means of charge to your credit card and you receive a confirmation.
			Upon making a purchase it becomes necessary for you to give your authorization to run the corresponding charge on your credit card and by this you declare to have full knowledge of our Reservation and Payment Policies, Disclaimer and Cancellation Policies. All reservations are subject to availability existing at the moment of your request. No confirmation can be issued until full payment for the requested service has been made. In some cases (which are duly marked for you to easily identify them before filling out contact information and credit card number fields) it will be necessary to check availability directly with the service operator before a confirmation can be issued to you. Please note that this verification and confirmation process may take up to, and never more than, 24 hours.
			In order to avoid inconveniences, please make a printout of your reservation voucher and have it ready for check-in to the reserved service. Should a change to a confirmed reservation be needed, please contact your assigned preferencepass toll free number and have your reservation and/or confirmation number handy. We strongly suggest reading the CANCELLATION POLICIES section hereinafter. Any changes are subject to availability and rate adjustments when necessary. Our CANCELLATION POLICIES are applicable at all times without exception.
			<br><br>
			<h2>PAYMENT POLICIES:</h2>
			The amount corresponding to your purchase will be immediately charged to your credit card, provided it has a confirmed reservation status. Please bear in mind that your credit card billing statement will show "Preference Pass Holding Ltd" as the company responsible for all charges. 
			VISA, MASTERCARD and AMERICAN EXPRESS and all other payments methods are welcome.
			The currency in which service rates are quoted on the website is US dollars, in which case the specific currency will be readily specified for your easy identification statement. <a routerLink="/">www.preferencepass.com</a> cannot be held responsible for this variation and upon accepting the PAYMENT POLICIES you acknowledge to have been informed of the exchange rate fluctuation and declare your agreement to the corresponding charge being made in US Dollars.
			<br><br>
			<h2>DISCLAIMER:</h2>
			<a routerLink="/">www.preferencepass.com</a>  works as a middle-agent between the client and the operator of services listed on the website. As such, <a routerLink="/">www.preferencepass.com</a>  creates the necessary commercial connections in compliance with its own service and quality standards to provide services such as, but not limited to, tours, restaurants, traveling, Doctors, shopping etc. Only the most reputable suppliers are selected for this purpose. However <a routerLink="/">www.preferencepass.com</a> cannot be held liable for their acts, omission, wrongdoing or other. Travel services are subject to the conditions set by those suppliers, and their liability may, in turn, be limited by their tariffs and conditions of service. <a routerLink="/">www.preferencepass.com</a>acts only in its role of agent for the client or for the supplier of the goods and services rendered and as such, does not keep any legal authority or control over the operator’s Personnel, assets, operation and/or property.
			<a routerLink="/">www.preferencepass.com</a> herewith declares that,
			<div><b>(a)</b> Photographic material published on its website is intended to render a general depiction of the service in question and by no means can be guaranteed that the service will be supplied exactly as depicted.</div>
			<div><b>(c)</b> Travel services descriptions are regularly updated for a depiction of the product as close to reality as possible. However, <a routerLink="/">www.preferencepass.com</a> cannot be held accountable for variations occurring upon your arrival at the Travel Service site.</div>
			<div><b>(d)</b> <a routerLink="/">www.preferencepass.com</a> will reserve the right to deny the supply of a service to any client at any given moment if and when it considers convenient to do so.</div>
			<div><b>(e)</b> Any claim or comments that the client should present about the services received must be submitted in writing within a period of time no longer than 14 (fourteen) days from purchase date.</div>
			Preferencepass will not assume liability for any claims, costs or expenses arising from personal injuries to the client or third parties, or caused by accidents, fatalities, loss or damage to personal property, lack of enjoyment or claims over emotional and mental states such as upset, disappointment, anguish, distress or frustration, or any other damage, whether physical, mental or emotional, arising from the following:
			<div><b>(a)</b> Acts committed or omissions caused by any party other than <a routerLink="/">www.preferencepass.com</a> or its employees.</div>
			<div><b>(b)</b> Illness, theft, labor disputes, mechanical failures, quarantine, Government actions, weather or any other circumstance beyond direct control of <a routerLink="/">www.preferencepass.com</a>.</div>
			<div><b>(c)</b> The client’s failure to obtain the required travel documentation no refund will be granted.</div>
			<div><b>(d)</b> The client’s failure to comply with travel instructions such as, but not limited to, time schedules, pick up, check-in and check-out dates and times, and voucher redemption policies.</div>
			<div><b>(e)</b> Changes to, or cancellation of, the travel services offered, notwithstanding the reason. <a routerLink="/">www.preferencepass.com</a> reserves the right to cancel or change the travel services at its discretion, but will try to substitute them with comparable services. If a reservation must completely be canceled, <a routerLink="/">www.preferencepass.com</a>’s liability will be limited to a refund of all monies paid to <a routerLink="/">www.preferencepass.com</a>.</div>
			<div><b>(f)</b> A full refund will not be granted by <a routerLink="/">www.preferencepass.com</a> in situations when a service must be interrupted, postponed or cancelled for reasons beyond its control (acts of God such as bad weather -including hurricanes- , earthquakes or war, acts of terrorism or else), circumstances under which <a routerLink="/">www.preferencepass.com</a> is not allowed to obtain full refund from service operators in view of specific contract terms. In order to cover book-keeping and administration services, <a routerLink="/">www.preferencepass.com</a> will be thus entitled to up to a 10% retention upon the total amount paid by the client for his/her reservation.</div>
			Despite our close communication with our selected group of service suppliers, there is still a possibility that changes on the rates may occur without notice. As some of the rates become expired and cannot be timely updated by the operator to your immediate convenience, <a routerLink="/">www.preferencepass.com</a> regularly runs a rates verification process which may yield differences between the price you have paid for your reservation and the price you need to pay to actually enjoy the service. When an updated rate happens to be lower than the originally offered to you, <a routerLink="/">www.preferencepass.com</a> will only charge the lower amount. When an updated price is higher than the originally quoted price, <a routerLink="/">www.preferencepass.com</a> will have a Travel Consultant inform you of the specific variation and the resulting balance that needs to be covered. Should you not agree to the correct amount and decide to cancel upon the circumstances, <a routerLink="/">www.preferencepass.com</a> will honor you cancellation request without penalization. <a routerLink="/">www.preferencepass.com</a> and its service suppliers will also be released from any responsibility towards compensations that the client may claim and will not be considered liable for any inconveniences arising from the said rate difference and/or cancellation.
			<b>-Disclaimer "U.S. Citizens"/Cuba-</b> If you are a citizen of the United States of America (USA), or a company controlled or under the ownership of a body of the USA, and therefore  relevant to the program administered by <b>The Cuban Assets Control Regulations (“CACR”)</b>, and under the regulation <b>31. C.F.R. § S15</b>, or you are prohibited from acquiring tourist services to Cuba.  In the event of acquiring any tourist service to Cuba of those offered on this site, you declare and will be responsible for complying with all the requirements provided under said regulation and any corresponding law, rule or regulation established for that purpose by the USA and/or the <b>Department of Treasury’s Office of Foreign Assets Controls (“OFAC”)</b>.
			<br><br>
			<h2>CANCELLATION POLICIES:</h2>
			All cancellation requests must be addressed in writing to <a href="mailto:sales@preferencepass.com">info@preferencepass.com</a> with the transactions number as the basis reference.
			In case of tours and any other service:
			At the moment of reserving, specific cancellation policies by the operator to which you are requesting will automatically be displayed for your information. The following are general cancellation policies which are applicable for all payments.
			<div><b>-</b> Cancellation requests made 15 (fifteen) or more days prior to confirmed arrival date are subject to a penalization of 10% on the total paid for the membership fee.</div>
			<div><b>-</b> Cancellation requests made no more than 14 (fourteen) days and no less than 3 (three) days prior to the confirmed arrival date are subject to a penalization equal to the price of 2 (two) nights.</div>
			<div><b>-</b> Cancellation requests within 2 (two) days to the confirmed arrival date or a “no-show” are 100% non refundable. No refunds will be granted either for unused portions of the reservation due to an early departure.</div>
			<div><b>-</b> Different cancellation policies for reservations made for Christmas, New Year and Easter may apply. Please contact one of our Consultants for further details.</div>
			In case of tour and/or ground transportation reservations:
			At the moment of reserving, specific cancellation policies by the tour and transportation to which you are reserving will automatically be displayed for your information. The following are general cancellation policies which are applicable for most of our listed tours and transportation services:
			<div><b>-</b> Cancellation requests made 3 (three) or more days prior to the confirmed service date are subject to a 10% penalization on the total amount paid for the reservation.</div>
			<div><b>-</b> Cancellation requests within 2 (two) days to the confirmed service date or a “no-show” are 100% non refundable.</div>
		</div>
	`,
	styleUrls: ['./terms-and-conditions.component.scss']
})

export class TermsAndConditionsComponent implements OnInit {

	constructor() { }

	ngOnInit() { }
}